### ISSUE TITLE
Witherbringer Stack Trace

### ISSUE THREAD

**Issue by Parsonswy** [peacefulcraft-network/TrenchPvP#117]
```
[22:03:24] [Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to TrenchPvP v1.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1827) ~[spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassCastException: org.bukkit.event.player.PlayerInteractEntityEvent cannot be cast to org.bukkit.event.player.PlayerInteractEvent
at net.peacefulcraft.trenchpvp.gameclasses.abilities.Witherbringer.abilitySignature(Witherbringer.java:30) ~[?:?]
at net.peacefulcraft.trenchpvp.gameclasses.abilities.TrenchAbilityManager.abilityExecuteLoop(TrenchAbilityManager.java:40) ~[?:?]
at net.peacefulcraft.trenchpvp.gameclasses.listeners.AbilityClickListener.onPlayerClick(AbilityClickListener.java:47) ~[?:?]
at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15-0.jar:git-Spigot-047b6f8-e43416a]
```

**Comment by Parsonswy** [comment]
Clearing out old, unconfirmed bugs so we can start on a cleaner slate for Multi-Arena Q/A.
