### ISSUE TITLE
LaunchPad Stack Trace

### ISSUE THREAD

**Issue by Parsonswy** [peacefulcraft-network/TrenchPvP#118]
```
> [18:34:11] [Server thread/WARN]: [TrenchPvP] Task #2450 for TrenchPvP v1.0 generated an exception
java.lang.NullPointerException: null
at net.peacefulcraft.trenchpvp.gameclasses.abilities.LaunchPad$1.run(LaunchPad.java:67) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.1-1.jar:git-Spigot-492a779-731e819]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.1-1.jar:git-Spigot-492a779-731e819]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot-1.15.1-1.jar:git-Spigot-492a779-731e819]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1-1.jar:git-Spigot-492a779-731e819]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1-1.jar:git-Spigot-492a779-731e819]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1-1.jar:git-Spigot-492a779-731e819]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Parsonswy** [comment]
Clearing out old, unconfirmed bugs so we can start on a cleaner slate for Multi-Arena Q/A.
